### ISSUE TITLE
[Suggestion] Add Unlocking and locking sound events

### ISSUE THREAD

**Issue by Luximoz** [ORelio/Sound-Manager#9]
Why am I suggesting this? 
Ever since Windows 8, you can make Windows play a unique sound when unlocking the session called "Windows Unlock.wav" by default. 
(Ignore the XP Royale themed windows, I'm on a Windows 10 setup)
![Sound_w1](https://github.com/user-attachments/assets/7a683756-70d2-469d-bca5-a10cd76a8a8b)
![Registry Editor 1_w1](https://github.com/user-attachments/assets/f5e6b509-0feb-450f-83fb-bca88246bedb)

Another reason, which explains why I'm also suggesting a lock sound as well is because in Windows XP, the shutdown sound would also play when logging off, while the logoff sound would only play if you lock your session, while the startup sound always plays whenever you sign in and the logon sound would only play whenever you unlock your session.

So, currently, it is impossible to replicate Windows XP and older versions' behavior with Sound Manager

**Comment by ORelio** [comment]
Hi,

Thanks for this detailed suggestion.

**Regarding the Unlock sound**

Honestly, I was not aware this sound existed. I went and checked under Windows 7, 8, 10 and 11, and cannot find that sound in the Sound panel, alrhough it is indeed present in registry starting with Windows 8:

Windows 7 - Not present in registry - Regular Logoff/Logon sounds heard when locking then unlocking the session.
![image](https://github.com/user-attachments/assets/858daaf7-0994-41e6-8bab-b5544c7997dc)

Windows 8 - Present in registry, not present in Sound panel. No sound heard when locking then unlocking the session.
![image](https://github.com/user-attachments/assets/0ebc3324-8d2b-4b22-9b89-3a98c5c88ccc)

Windows 10 - Present in registry, not present in Sound panel. No sound heard when locking then unlocking the session.
![image](https://github.com/user-attachments/assets/3fe99eea-0cd5-48a9-8002-60517ece3991)

Windows 11 - Present in registry, not present in Sound panel. No sound heard when locking then unlocking the session.
![image](https://github.com/user-attachments/assets/cf2e0c95-6657-4e90-8691-990ade89eff0)

I could not get this sound event to work, but this should not be an issue, see below.

**Regarding sound event implementation**

On Windows Vista & 7, the following sounds should should be heard for the following events:

* First logon after boot: _built-in startup sound from the system_
  (Except Vista which plays built-in sound before logon, so first logon after boot plays the _Logon sound_)
* Switch user: _Logoff sound_
* Lock workstation: _Logoff sound_
* Logoff: _Logoff sound_
* Resume session: _Logon sound_
* Unlock workstation: _Logon sound_
* Subsequent logon after boot: _Logon sound_
* Shutdown system: _Shutdown sound_

Since Windows 8 and above play no Logon, Logoff or Unlock sound from my testing, I reimplemented the sounds in SoundManager as they were played before by explorer.exe, so they should be the same as Windows 7:

* Launching the SoundManager process: Determine what sound to play
  * First launch after reboot:
    * _Play Windows startup sound_ disabled in the Sound applet: _Startup sound_
    * _Play Windows startup sound_ enabled in the Sound applet:  _Nothing_
  * Subsequent launch: _Logon sound_
* SessionLock event: _Logoff sound_
  * This event also fires when switching users
* SessionUnlock event: _Logon sound_
  * This event also fires when switching users
* Application close event: Determine what sound to play
  * If the event cause is _System shutdown_ then play _Shutdown sound_
  * Otherwise, play _Logoff sound_

Indeed, Windows XP has the following behavior regarding _Subsequent logon after boot_ and _Logoff_:

* First logon after boot: _Startup Sound_
* Switch user: _Logoff sound_
* Lock workstation: _Logoff sound_
* Logoff: **_Shutdown sound_**
* Resume session: _Logon sound_
* Unlock workstation: _Logon sound_
* Subsequent logon after boot: **_Startup sound_**
* Shutdown system: _Shutdown sound_

I never really payed attention to this difference because I rarely login again or logoff on my own computer. I think the easiest fix will be adding a setting in config file you'll be able to toggle to have XP behavior for subsequent logons and logoff:

* Launching the SoundManager process: Determine what sound to play
  * First launch after reboot:
    * _Play Windows startup sound_ disabled in the Sound applet: _Startup sound_
    * _Play Windows startup sound_ enabled in the Sound applet: _Nothing_
  * Subsequent launch:
    * **XP MODE**: _Startup sound_
    * Otherwise: _Logon sound_
* SessionLock event: _Logoff sound_
  * This event also fires when switching users
* SessionUnlock event: _Logon sound_
  * This event also fires when switching users
* Application close event: Determine what sound to play
  * If the event cause is _System shutdown_ **OR XP MODE** then play _Shutdown sound_
  * Otherwise, play _Logoff sound_

Putting that on the TODO list.

**Comment by ORelio** [comment]
Hi,

I've implemented the changes in the following test build:
📁 [sound-manager-v3.3.0 TEST 2024-09-19.zip](https://github.com/user-attachments/files/17061103/sound-manager-v3.3.0.TEST.2024-09-19.zip)

You can enable the so-called "XP Mode" by going to _Settings > Edit config file_, then setting `PreferStartupSoundOnLogon=True`. You will need to log off and log on again to apply.

Let me know it this suits your needs so that I add this in the main codebase.

**Comment by ORelio** [comment]
Implemented in commit 3257416fbbde9334950ee5596615f4b38f39cfb4 that will be included in next release.

**Comment by ORelio** [comment]
Feature included in [SoundManager v3.3.1](https://github.com/ORelio/Sound-Manager/releases/tag/v3.3.1).
